// autogenerated by ../generate-errors.js
// regenerate when new error types are added anywhere in the project.
// to regenerate: npm run build && node ./generate-errors

import { ErrNoDefinition } from "./de";

export type AnyError = ReturnType<typeof ErrNoDefinition>;

const ERROR_CODES = new Set(["NoDefinition"]);

export function isAnyError(o: any): o is AnyError {
  return ERROR_CODES.has(o?.code);
}
